const mongoose = require("mongoose");

const invoiceSchema = new mongoose.Schema(
  {
    // Custom tracking fields
    verified: {
      type: Boolean,
      default: false,
    },
    dateStored: {
      type: Date,
      default: Date.now,
    },
    tag: {
      type: String,
      enum: ["Own Company", "External Delivery", "Own Delivery", "None"],
      default: "None",
    },
    paymentMethod: {
      type: String,
      enum: [
        "POS-Cash",
        "POS-Cheque",
        "POS-Credit",
        "Delivery-Cash",
        "Delivery-Cheque",
        "Delivery-Credit",
        "Unknown",
      ],
      default: "Unknown",
    },
    isPOS: {
      type: Boolean,
      default: false,
    },
    isDelivery: {
      type: Boolean,
      default: false,
    },

    // Original SAP B1 fields
    DocEntry: {
      type: Number,
      required: true,
      unique: true,
    },
    DocNum: {
      type: Number,
      required: true,
    },
    DocType: String,
    HandWritten: String,
    Printed: String,
    DocDate: Date,
    DocDueDate: Date,
    CardCode: String,
    CardName: String,
    Address: String,
    NumAtCard: String,
    DocTotal: Number,
    AttachmentEntry: String,
    DocCurrency: String,
    DocRate: Number,
    Reference1: String,
    Reference2: String,
    Comments: String,
    JournalMemo: String,
    PaymentGroupCode: Number,
    DocTime: String,
    SalesPersonCode: Number,
    TransportationCode: Number,
    Confirmed: String,
    ImportFileNum: String,
    SummeryType: String,
    ContactPersonCode: String,
    ShowSCN: String,
    Series: Number,
    TaxDate: Date,
    PartialSupply: String,
    DocObjectCode: String,
    ShipToCode: String,
    Indicator: String,
    FederalTaxID: String,
    DiscountPercent: Number,
    PaymentReference: String,
    CreationDate: Date,
    UpdateDate: Date,
    FinancialPeriod: Number,
    UserSign: Number,
    TransNum: Number,
    VatSum: Number,
    VatSumSys: Number,
    VatSumFc: Number,
    NetProcedure: String,
    DocTotalFc: Number,
    DocTotalSys: Number,
    Form1099: String,
    Box1099: String,
    RevisionPo: String,
    RequriedDate: Date,
    CancelDate: Date,
    BlockDunning: String,
    Submitted: String,
    Segment: Number,
    PickStatus: String,
    Pick: String,
    PaymentBlock: String,
    PaymentBlockEntry: String,
    CentralBankIndicator: String,
    MaximumCashDiscount: String,
    Reserve: String,
    Project: String,
    ExemptionValidityDateFrom: Date,
    ExemptionValidityDateTo: Date,
    WareHouseUpdateType: String,
    Rounding: String,
    ExternalCorrectedDocNum: String,
    InternalCorrectedDocNum: String,
    NextCorrectingDocument: String,
    DeferredTax: String,
    TaxExemptionLetterNum: String,
    WTApplied: Number,
    WTAppliedFC: Number,
    BillOfExchangeReserved: String,
    AgentCode: String,
    WTAppliedSC: Number,
    TotalEqualizationTax: Number,
    TotalEqualizationTaxFC: Number,
    TotalEqualizationTaxSC: Number,
    NumberOfInstallments: Number,
    ApplyTaxOnFirstInstallment: String,
    WTNonSubjectAmount: Number,
    WTNonSubjectAmountSC: Number,
    WTNonSubjectAmountFC: Number,
    WTExemptedAmount: Number,
    WTExemptedAmountSC: Number,
    WTExemptedAmountFC: Number,
    BaseAmount: Number,
    BaseAmountSC: Number,
    BaseAmountFC: Number,
    WTAmount: Number,
    WTAmountSC: Number,
    WTAmountFC: Number,
    VatDate: Date,
    DocumentsOwner: String,
    FolioPrefixString: String,
    FolioNumber: String,
    DocumentSubType: String,
    BPChannelCode: String,
    BPChannelContact: String,
    Address2: String,
    DocumentStatus: String,
    PeriodIndicator: String,
    PayToCode: String,
    ManualNumber: String,
    UseShpdGoodsAct: String,
    IsPayToBank: String,
    PayToBankCountry: String,
    PayToBankCode: String,
    PayToBankAccountNo: String,
    PayToBankBranch: String,
    BPL_IDAssignedToInvoice: String,
    DownPayment: Number,
    ReserveInvoice: String,
    LanguageCode: Number,
    TrackingNumber: String,
    PickRemark: String,
    ClosingDate: Date,
    SequenceCode: String,
    SequenceSerial: String,
    SeriesString: String,
    SubSeriesString: String,
    SequenceModel: String,
    UseCorrectionVATGroup: String,
    TotalDiscount: Number,
    DownPaymentAmount: Number,
    DownPaymentPercentage: Number,
    DownPaymentType: String,
    DownPaymentAmountSC: Number,
    DownPaymentAmountFC: Number,
    VatPercent: Number,
    ServiceGrossProfitPercent: Number,
    OpeningRemarks: String,
    ClosingRemarks: String,
    RoundingDiffAmount: Number,
    RoundingDiffAmountFC: Number,
    RoundingDiffAmountSC: Number,
    Cancelled: String,
    SignatureInputMessage: String,
    SignatureDigest: String,
    CertificationNumber: String,
    PrivateKeyVersion: String,
    ControlAccount: String,
    InsuranceOperation347: String,
    ArchiveNonremovableSalesQuotation: String,
    GTSChecker: String,
    GTSPayee: String,
    ExtraMonth: Number,
    ExtraDays: Number,
    CashDiscountDateOffset: Number,
    StartFrom: String,
    NTSApproved: String,
    ETaxWebSite: String,
    ETaxNumber: String,
    NTSApprovedNumber: String,
    EDocGenerationType: String,
    EDocSeries: String,
    EDocNum: String,
    EDocExportFormat: String,
    EDocStatus: String,
    EDocErrorCode: String,
    EDocErrorMessage: String,
    DownPaymentStatus: String,
    GroupSeries: String,
    GroupNumber: String,
    GroupHandWritten: String,
    ReopenOriginalDocument: String,
    ReopenManuallyClosedOrCanceledDocument: String,
    CreateOnlineQuotation: String,
    POSEquipmentNumber: String,
    POSManufacturerSerialNumber: String,
    POSCashierNumber: String,
    ApplyCurrentVATRatesForDownPaymentsToDraw: String,
    ClosingOption: String,
    SpecifiedClosingDate: Date,
    OpenForLandedCosts: String,
    AuthorizationStatus: String,
    TotalDiscountFC: Number,
    TotalDiscountSC: Number,
    RelevantToGTS: String,
    BPLName: String,
    VATRegNum: String,
    AnnualInvoiceDeclarationReference: String,
    Supplier: String,
    Releaser: String,
    Receiver: String,
    BlanketAgreementNumber: String,
    IsAlteration: String,
    CancelStatus: String,
    AssetValueDate: Date,
    DocumentDelivery: String,
    AuthorizationCode: String,
    StartDeliveryDate: Date,
    StartDeliveryTime: String,
    EndDeliveryDate: Date,
    EndDeliveryTime: String,
    VehiclePlate: String,
    ATDocumentType: String,
    ElecCommStatus: String,
    ElecCommMessage: String,
    ReuseDocumentNum: String,
    ReuseNotaFiscalNum: String,
    PrintSEPADirect: String,
    FiscalDocNum: String,
    POSDailySummaryNo: String,
    POSReceiptNo: String,
    PointOfIssueCode: String,
    Letter: String,
    FolioNumberFrom: String,
    FolioNumberTo: String,
    InterimType: String,
    RelatedType: Number,
    RelatedEntry: String,
    SAPPassport: String,
    DocumentTaxID: String,
    DateOfReportingControlStatementVAT: Date,
    ReportingSectionControlStatementVAT: String,
    ExcludeFromTaxReportControlStatementVAT: String,
    POS_CashRegister: String,
    UpdateTime: String,
    CreateQRCodeFrom: String,
    PriceMode: String,
    Revision: String,
    OriginalRefNo: String,
    OriginalRefDate: Date,
    GSTTransactionType: String,
    OriginalCreditOrDebitNo: String,
    OriginalCreditOrDebitDate: Date,
    ECommerceOperator: String,
    ECommerceGSTIN: String,
    ShipFrom: String,
    CommissionTrade: String,
    CommissionTradeReturn: String,
    UseBillToAddrToDetermineTax: String,
    IssuingReason: Number,
    Cig: String,
    Cup: String,
    EDocType: String,
    PaidToDate: Number,
    PaidToDateFC: Number,
    PaidToDateSys: Number,
    BaseType: Number,
    BaseEntry: String,
    FatherCard: String,
    FatherType: String,
    ShipState: String,
    ShipPlace: String,
    CustOffice: String,
    FCI: String,
    AddLegIn: String,
    LegTextF: String,
    DANFELgTxt: String,
    IndFinal: String,
    DataVersion: Number,

    // Custom SAP B1 fields
    U_Route: String,
    U_Notes: String,
    U_CCSurcharge: String,
    U_SurchargeRate: Number,
    U_PrintedDate: Date,
    U_HHEmpID: String,
    U_EPOSNo: String,
    U_B1IFDocEntry: String,
    U_U_ROUTENUMBER: String,
    U_U_ROUTEPAYMETHOD: String,
    U_U_ROUTEORDER: String,
    U_U_ROUTEPAYAMOUNT: String,
    salesAgent: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },

    // Document lines array
    DocumentLines: [
      {
        LineNum: Number,
        ItemCode: String,
        ItemDescription: String,
        Quantity: Number,
        ShipDate: Date,
        Price: Number,
        PriceAfterVAT: Number,
        Currency: String,
        LineTotal: Number,
        VatGroup: String,
      },
    ],

    // Document approval requests array
    Document_ApprovalRequests: [
      {
        type: mongoose.Schema.Types.Mixed,
      },
    ],
  },
  {
    timestamps: true,
  }
);

const Invoice = mongoose.model("Invoices", invoiceSchema);

module.exports = Invoice;
